### ISSUE TITLE
Export struct fields in SecurePassword struct

### ISSUE THREAD

**Issue by ehernandez-xk** [Luzifer/password#1]
You are exporting the SecurePassword struct but not its fields
This can helps if you want to add custom config

```go
type SecurePassword struct {
	CharacterTables map[string]string
	InsecurePattern []string
	BadCharacters   []string
}
```

For example:

```go
package main

import (
	"fmt"

	password "github.com/Luzifer/password/lib"
)

func main() {

	//secPass := password.NewSecurePassword()
	secPass := &password.SecurePassword{
		CharacterTables: map[string]string{
			"numeric": "123456789",
			"simple":  "abcdefghijklmnopqrstuvwxyz",
			"special": "*-/",
		},
		BadCharacters: []string{"0", "O"},
	}
	pass, _ := secPass.GeneratePassword(25, false)

	fmt.Println(pass)

}
```

**Comment by Luzifer** [comment]
I've done the implementation of the requested export in #2 but currently I'm not sure about the contents of that PR. I'd love to gather more feedback about my thoughts over there, so if you have time for that please let my know your thoughts!

**Comment by ehernandez-xk** [comment]
Sorry for the delay.

I added a comment in the PR

**Comment by Luzifer** [comment]
Closing this for the same reason as #2: I'm not going to implement this but I uploaded a patch to the comments of #2 ready to be applied to a fork.

> This PR is laying around here for a year now and I decided not to merge it. The generator library is intended to generate strong passwords and therefore the rules are kept static.
