### ISSUE TITLE
build error on google appengine

### ISSUE THREAD

**Issue by ththvseo** [Luzifer/password#4]
i did not research in detail, but just FYI,
it appears that https://github.com/Luzifer/password/commit/2b8748e5a6cb33635ec6d0ff47646599857ba153 breaks the build on google appengine when github.com/pkg/errors is used by the same app:
```
RuntimeError: 2019/02/26 15:26:30 go-app-builder: Failed parsing input: package "github.com/pkg/errors" is imported from multiple locations: "/go/src/github.com/pkg/errors" and "/go/src/github.com/Luzifer/password/vendor/github.com/pkg/errors"
```

**Comment by Luzifer** [comment]
This was not limited to AppEngine but to all having the same imports as the library. A library should never vendor but as it was placed below a CLI util it had a `vendor`-folder.

Please update to `v2.0.3` which has no functional changes to the library itself but should solve the vendoring issue.

**Comment by ththvseo** [comment]
many thanks.
(i only noticed that our CI completed the local build but then failed on uploading to gae,
 and was in the process of just removing the library)

**Comment by ththvseo** [comment]
```
cannot find package "github.com/Luzifer/go_helpers/v2/http"
```
?

**Comment by Luzifer** [comment]
That one is only needed by `cmd/password`. Not by the library.

**Comment by ththvseo** [comment]
this says otherwise:
https://github.com/Luzifer/password/blob/eed2ae8b0814ffdcb05b4d463d5547564929186d/lib/xkcd.go#L9

and it seems you did not upload that package?

**Comment by ththvseo** [comment]
anyway, many thanks for your efforts,
i replaced the package with a local fork by now, to fix my build.

as noted above, i only reported this FYI.
