### ISSUE TITLE
Add on option to choose the number of special chars

### ISSUE THREAD

**Issue by soullivaneuh** [Luzifer/password#7]
On some customer cases, generated password contains to much special chars, for example: `h,~h,Uq4dJE=+Jp!-$9H`

May we consider an option to adjust the number of special chars?

**Comment by Luzifer** [comment]
I agree, that particular password is kinda, well, trash… I wouldn't use that either.

On the other hand: It's purely random. You can just use the next one being generated which most likely will not contain an insane amount of special characters.

I don't see how a limit of special characters improves the generator especially as different length of passwords may contain different amounts of special characters.
