### ISSUE TITLE
Avoid ambigous chars option

### ISSUE THREAD

**Issue by soullivaneuh** [Luzifer/password#8]
As an alternative or in addition to #7, we may propose an option to avoid ambiguous character like this service do: https://passwordsgenerator.net/

This allows to generate strong and secure password but not hard to read or type on keyboard.

**Comment by Luzifer** [comment]
There is already a list of characters not being used as of being not clear when not using serif-fonts:

https://github.com/Luzifer/password/blob/master/lib/generator.go#L46
